[project]
name = "onyxsh"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Terminals :: Terminal Emulators/X Terminals",
]
version = "0.9.0"
authors = [
    { name = "Leonardo Berbert", email = "leo4berbert@gmail.com" },
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["PyGObject", "pycairo", "setproctitle", "requests", "psutil", "pycryptodomex", "regex; extra == 'performance'", "Pygments; extra == 'syntax-highlighting'", "py7zr; extra == 'backup'"]

[project.gui-scripts]
onyxsh = "onyxsh:main"

[project.urls]
Homepage = "https://github.com/VaGNaroK/OnyxSH"
Issues = "https://github.com/VaGNaroK/OnyxSH/issues"

[project.optional-dependencies]
performance = ["regex"]
syntax-highlighting = ["Pygments"]
backup = ["py7zr"]
dev = ["pytest", "pytest-asyncio"]
all = ["regex", "Pygments", "py7zr", "pytest", "pytest-asyncio"]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
include = ["onyxsh"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
onyxsh = ["**/*"]

[tool.setuptools.data-files]
"share/applications" = ["usr/share/applications/io.github.vagnarok.OnyxSH.desktop"]
"share/icons/hicolor/scalable/apps" = ["usr/share/icons/hicolor/scalable/apps/onyxsh.svg"]
"share/pixmaps" = ["usr/share/icons/hicolor/scalable/apps/onyxsh.svg"]
"share/kio/servicemenus" = ["usr/share/kio/servicemenus/onyxsh.desktop", "usr/share/kio/servicemenus/onyxsh-remote.desktop"]
"share/nautilus-python/extensions" = ["usr/share/nautilus-python/extensions/onyxsh.py"]
"share/nemo/actions" = ["usr/share/nemo/actions/onyxsh.nemo_action", "usr/share/nemo/actions/onyxsh-remote.nemo_action"]
"share/polkit-1/actions" = ["usr/share/polkit-1/actions/io.github.vagnarok.OnyxSH.policy"]
